- hosts: jenkins-server
  tasks:
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes
    become: yes

  - name: Upgrade all apt packages
    apt:
      upgrade: dist
      force_apt_get: yes
    become: yes

  - name: Reboot the machine
    reboot:
    become: yes

  - name: Create File README.md
    copy:
      dest: /home/ubuntu/README.md
      content: "Ubuntu 20.04 LTS - System Ready!"

  - name: Install Java OpenJDK 11
    apt:
      name: openjdk-11-jdk
      state: present
      force_apt_get: yes
    become: yes

  - name: Add apt-key of jenkins repo
    shell: "wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -"

  - name: Add Jenkins on repo source list
    shell: "sh -c 'echo deb https://pkg.jenkins.io/debian binary/ > /etc/apt/sources.list.d/jenkins.list'"
    become: yes
  
  - name: Update apt-get repo and cache after add jenkins
    apt: 
      update_cache: yes
    become: yes
  
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
      force_apt_get: yes
    become: yes

  - name: Jenkins Initial Admin Password
    shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
    become: yes